sed -i 's@START_TEST("1: rba_BldrCmp_RC_EraseMemory",@START_TEST("100: rba_BldrCmp_RC_EraseMemory",@g' 'C:/Users/hieu.nguyen-trung/Desktop/Test_Folder/a.c'
sed -i 's@START_TEST("2: rba_BldrCmp_RC_EraseMemory",@START_TEST("101: rba_BldrCmp_RC_EraseMemory",@g' 'C:/Users/hieu.nguyen-trung/Desktop/Test_Folder/a.c'
sed -i 's@START_TEST("3: rba_BldrCmp_RC_EraseMemory",@START_TEST("102: rba_BldrCmp_RC_EraseMemory",@g' 'C:/Users/hieu.nguyen-trung/Desktop/Test_Folder/a.c'
sed -i 's@START_TEST("4: rba_BldrCmp_RC_EraseMemory",@START_TEST("103: rba_BldrCmp_RC_EraseMemory",@g' 'C:/Users/hieu.nguyen-trung/Desktop/Test_Folder/a.c'
sed -i 's@START_TEST("5: rba_BldrCmp_RC_EraseMemory",@START_TEST("104: rba_BldrCmp_RC_EraseMemory",@g' 'C:/Users/hieu.nguyen-trung/Desktop/Test_Folder/a.c'
